export default [
    {
        id:1,
        postedOn : '2026-01-12',
        title: 'iOS Developer',
        company: 'Apple',
        type: 'Full Time',
        experience: 'Mid Level',
        location: 'Remote',
        skills: ["SwiftUI", "UiKit", "Core Data"],
        job_link: "https://www.apple.com/careers/in/",
    },
    {
        id: 2,
        postedOn: '2026-01-02',
        title: "Frontend Developer",
        type: "Full time",
        location: "In-office",
        experience: "Fresher",
        company: "Amazon",
        skills: ["Javascript", "Nextjs", "Tailwind CSS"],
        job_link: "https://www.amazon.jobs/en/",
      },
      {
        id: 3,
        postedOn: '2026-01-02',
        title: "Android Developer",
        type: "Part time",
        location: "Remote",
        experience: "Senior Level",
        company: "Facebook",
        skills: ["Kotlin", "MVVM"],
        job_link: "https://facebook.com/careers",
      },
      {
        id: 4,
        postedOn: '2025-11-01',
        title: "Developer Advocate",
        type: "Contract",
        location: "Hybrid",
        experience: "Junior Level",
        company: "Netflix",
        companyUrl: "https://facebook.com",
        skills: ["web3", "Content Creation", "Community"],
        job_link: "https://jobs.netflix.com/",
      },
      {
    id: 5,
    postedOn: '2026-01-14',
    title: "Backend Developer",
    type: "Full Time",
    location: "Remote",
    experience: "Mid Level",
    company: "Google",
    skills: ["Node.js", "Express", "MongoDB", "REST APIs"],
    job_link: "https://careers.google.com/jobs/results/",
}

]